2023-03-14 15:30:58,516 INFO    MainThread:26364 [internal.py:wandb_internal():90] W&B internal server running at pid: 26364, started at: 2023-03-14 15:30:58.516805
2023-03-14 15:30:58,516 INFO    WriterThread:26364 [datastore.py:open_for_write():75] open: C:\Users\jaydenpark\Documents\GitHub\disaster_tweet\wandb\run-20230314_153057-3kdb8mwr\run-3kdb8mwr.wandb
2023-03-14 15:30:58,751 DEBUG   SenderThread:26364 [sender.py:send():235] send: header
2023-03-14 15:30:58,751 DEBUG   SenderThread:26364 [sender.py:send():235] send: run
2023-03-14 15:30:59,032 DEBUG   HandlerThread:26364 [handler.py:handle_request():141] handle_request: check_version
2023-03-14 15:30:59,047 INFO    SenderThread:26364 [dir_watcher.py:__init__():205] watching files in: C:\Users\jaydenpark\Documents\GitHub\disaster_tweet\wandb\run-20230314_153057-3kdb8mwr\files
2023-03-14 15:30:59,047 INFO    SenderThread:26364 [sender.py:_start_run_threads():812] run started: 3kdb8mwr with start time 1678775457
2023-03-14 15:30:59,047 DEBUG   SenderThread:26364 [sender.py:send():235] send: summary
2023-03-14 15:30:59,047 INFO    SenderThread:26364 [sender.py:_save_file():949] saving file wandb-summary.json with policy end
2023-03-14 15:30:59,047 DEBUG   SenderThread:26364 [sender.py:send_request():249] send_request: check_version
2023-03-14 15:30:59,079 DEBUG   HandlerThread:26364 [handler.py:handle_request():141] handle_request: run_start
2023-03-14 15:30:59,094 DEBUG   HandlerThread:26364 [meta.py:__init__():35] meta init
2023-03-14 15:30:59,094 DEBUG   HandlerThread:26364 [meta.py:__init__():49] meta init done
2023-03-14 15:30:59,094 DEBUG   HandlerThread:26364 [meta.py:probe():209] probe
2023-03-14 15:30:59,126 DEBUG   HandlerThread:26364 [meta.py:_save_pip():53] save pip
2023-03-14 15:30:59,126 DEBUG   HandlerThread:26364 [meta.py:_save_pip():67] save pip done
2023-03-14 15:30:59,126 DEBUG   HandlerThread:26364 [meta.py:_save_conda():74] save conda
2023-03-14 15:30:59,126 ERROR   HandlerThread:26364 [meta.py:_save_conda():83] Error saving conda packages
Traceback (most recent call last):
  File "C:\Users\jaydenpark\Anaconda3\envs\nlp3\lib\site-packages\wandb\sdk\internal\meta.py", line 79, in _save_conda
    subprocess.call(
  File "C:\Users\jaydenpark\Anaconda3\envs\nlp3\lib\subprocess.py", line 349, in call
    with Popen(*popenargs, **kwargs) as p:
  File "C:\Users\jaydenpark\Anaconda3\envs\nlp3\lib\subprocess.py", line 951, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "C:\Users\jaydenpark\Anaconda3\envs\nlp3\lib\subprocess.py", line 1420, in _execute_child
    hp, ht, pid, tid = _winapi.CreateProcess(executable, args,
FileNotFoundError: [WinError 2] 지정된 파일을 찾을 수 없습니다
2023-03-14 15:30:59,126 DEBUG   HandlerThread:26364 [meta.py:_save_conda():84] save conda done
2023-03-14 15:30:59,126 DEBUG   HandlerThread:26364 [meta.py:probe():247] probe done
2023-03-14 15:30:59,329 DEBUG   SenderThread:26364 [sender.py:send():235] send: files
2023-03-14 15:30:59,329 INFO    SenderThread:26364 [sender.py:_save_file():949] saving file wandb-metadata.json with policy now
2023-03-14 15:30:59,347 DEBUG   HandlerThread:26364 [handler.py:handle_request():141] handle_request: stop_status
2023-03-14 15:30:59,348 DEBUG   SenderThread:26364 [sender.py:send_request():249] send_request: stop_status
2023-03-14 15:30:59,351 DEBUG   HandlerThread:26364 [handler.py:handle_request():141] handle_request: pause
2023-03-14 15:30:59,351 INFO    HandlerThread:26364 [handler.py:handle_request_pause():695] stopping system metrics thread
2023-03-14 15:30:59,436 DEBUG   HandlerThread:26364 [handler.py:handle_request():141] handle_request: resume
2023-03-14 15:30:59,436 INFO    HandlerThread:26364 [handler.py:handle_request_resume():686] starting system metrics thread
2023-03-14 15:30:59,436 DEBUG   HandlerThread:26364 [handler.py:handle_request():141] handle_request: pause
2023-03-14 15:30:59,436 INFO    HandlerThread:26364 [handler.py:handle_request_pause():695] stopping system metrics thread
2023-03-14 15:30:59,483 DEBUG   HandlerThread:26364 [handler.py:handle_request():141] handle_request: resume
2023-03-14 15:30:59,483 INFO    HandlerThread:26364 [handler.py:handle_request_resume():686] starting system metrics thread
2023-03-14 15:30:59,546 DEBUG   HandlerThread:26364 [handler.py:handle_request():141] handle_request: pause
2023-03-14 15:30:59,546 INFO    HandlerThread:26364 [handler.py:handle_request_pause():695] stopping system metrics thread
2023-03-14 15:30:59,556 DEBUG   SenderThread:26364 [sender.py:send():235] send: telemetry
2023-03-14 15:30:59,557 DEBUG   SenderThread:26364 [sender.py:send():235] send: stats
2023-03-14 15:30:59,557 DEBUG   SenderThread:26364 [sender.py:send():235] send: stats
2023-03-14 15:30:59,675 DEBUG   HandlerThread:26364 [handler.py:handle_request():141] handle_request: resume
2023-03-14 15:30:59,675 INFO    HandlerThread:26364 [handler.py:handle_request_resume():686] starting system metrics thread
2023-03-14 15:30:59,675 DEBUG   SenderThread:26364 [sender.py:send():235] send: stats
2023-03-14 15:31:00,053 INFO    Thread-7  :26364 [dir_watcher.py:_on_file_created():256] file/dir created: C:\Users\jaydenpark\Documents\GitHub\disaster_tweet\wandb\run-20230314_153057-3kdb8mwr\files\wandb-summary.json
2023-03-14 15:31:00,053 INFO    Thread-7  :26364 [dir_watcher.py:_on_file_created():256] file/dir created: C:\Users\jaydenpark\Documents\GitHub\disaster_tweet\wandb\run-20230314_153057-3kdb8mwr\files\wandb-metadata.json
2023-03-14 15:31:00,053 INFO    Thread-7  :26364 [dir_watcher.py:_on_file_created():256] file/dir created: C:\Users\jaydenpark\Documents\GitHub\disaster_tweet\wandb\run-20230314_153057-3kdb8mwr\files\output.log
2023-03-14 15:31:00,053 INFO    Thread-7  :26364 [dir_watcher.py:_on_file_created():256] file/dir created: C:\Users\jaydenpark\Documents\GitHub\disaster_tweet\wandb\run-20230314_153057-3kdb8mwr\files\conda-environment.yaml
2023-03-14 15:31:00,053 INFO    Thread-7  :26364 [dir_watcher.py:_on_file_created():256] file/dir created: C:\Users\jaydenpark\Documents\GitHub\disaster_tweet\wandb\run-20230314_153057-3kdb8mwr\files\requirements.txt
2023-03-14 15:31:00,215 INFO    Thread-11 :26364 [upload_job.py:push():132] Uploaded file C:\Users\JAYDEN~1\AppData\Local\Temp\2\tmpe6mjj_g4wandb\9d4yvvnp-wandb-metadata.json
2023-03-14 15:31:02,065 INFO    Thread-7  :26364 [dir_watcher.py:_on_file_modified():269] file/dir modified: C:\Users\jaydenpark\Documents\GitHub\disaster_tweet\wandb\run-20230314_153057-3kdb8mwr\files\output.log
2023-03-14 15:31:04,076 INFO    Thread-7  :26364 [dir_watcher.py:_on_file_modified():269] file/dir modified: C:\Users\jaydenpark\Documents\GitHub\disaster_tweet\wandb\run-20230314_153057-3kdb8mwr\files\output.log
2023-03-14 15:31:06,909 DEBUG   HandlerThread:26364 [handler.py:handle_request():141] handle_request: pause
2023-03-14 15:31:06,909 INFO    HandlerThread:26364 [handler.py:handle_request_pause():695] stopping system metrics thread
2023-03-14 15:31:06,957 DEBUG   HandlerThread:26364 [handler.py:handle_request():141] handle_request: resume
2023-03-14 15:31:06,957 INFO    HandlerThread:26364 [handler.py:handle_request_resume():686] starting system metrics thread
2023-03-14 15:31:06,957 DEBUG   HandlerThread:26364 [handler.py:handle_request():141] handle_request: pause
2023-03-14 15:31:06,957 INFO    HandlerThread:26364 [handler.py:handle_request_pause():695] stopping system metrics thread
2023-03-14 15:31:07,037 DEBUG   SenderThread:26364 [sender.py:send():235] send: stats
2023-03-14 15:31:07,037 DEBUG   SenderThread:26364 [sender.py:send():235] send: stats
2023-03-14 15:31:14,557 DEBUG   HandlerThread:26364 [handler.py:handle_request():141] handle_request: stop_status
2023-03-14 15:31:14,559 DEBUG   SenderThread:26364 [sender.py:send_request():249] send_request: stop_status
2023-03-14 15:31:29,257 INFO    Thread-7  :26364 [dir_watcher.py:_on_file_modified():269] file/dir modified: C:\Users\jaydenpark\Documents\GitHub\disaster_tweet\wandb\run-20230314_153057-3kdb8mwr\files\config.yaml
2023-03-14 15:31:29,820 DEBUG   HandlerThread:26364 [handler.py:handle_request():141] handle_request: stop_status
2023-03-14 15:31:29,820 DEBUG   SenderThread:26364 [sender.py:send_request():249] send_request: stop_status
2023-03-14 15:31:45,031 DEBUG   HandlerThread:26364 [handler.py:handle_request():141] handle_request: stop_status
2023-03-14 15:31:45,031 DEBUG   SenderThread:26364 [sender.py:send_request():249] send_request: stop_status
2023-03-14 15:32:00,869 DEBUG   HandlerThread:26364 [handler.py:handle_request():141] handle_request: stop_status
2023-03-14 15:32:00,869 DEBUG   SenderThread:26364 [sender.py:send_request():249] send_request: stop_status
2023-03-14 15:32:04,316 DEBUG   SenderThread:26364 [sender.py:send():235] send: telemetry
2023-03-14 15:32:04,370 DEBUG   SenderThread:26364 [sender.py:send():235] send: exit
2023-03-14 15:32:04,370 INFO    SenderThread:26364 [sender.py:send_exit():371] handling exit code: 0
2023-03-14 15:32:04,370 INFO    SenderThread:26364 [sender.py:send_exit():373] handling runtime: 7
2023-03-14 15:32:04,370 DEBUG   HandlerThread:26364 [handler.py:handle_request():141] handle_request: poll_exit
2023-03-14 15:32:04,370 INFO    SenderThread:26364 [sender.py:_save_file():949] saving file wandb-summary.json with policy end
2023-03-14 15:32:04,370 INFO    SenderThread:26364 [sender.py:send_exit():379] send defer
2023-03-14 15:32:04,370 DEBUG   SenderThread:26364 [sender.py:send_request():249] send_request: poll_exit
2023-03-14 15:32:04,370 DEBUG   HandlerThread:26364 [handler.py:handle_request():141] handle_request: defer
2023-03-14 15:32:04,370 INFO    HandlerThread:26364 [handler.py:handle_request_defer():164] handle defer: 0
2023-03-14 15:32:04,370 DEBUG   SenderThread:26364 [sender.py:send_request():249] send_request: defer
2023-03-14 15:32:04,370 INFO    SenderThread:26364 [sender.py:send_request_defer():388] handle sender defer: 0
2023-03-14 15:32:04,370 INFO    SenderThread:26364 [sender.py:transition_state():392] send defer: 1
2023-03-14 15:32:04,370 DEBUG   HandlerThread:26364 [handler.py:handle_request():141] handle_request: defer
2023-03-14 15:32:04,370 INFO    HandlerThread:26364 [handler.py:handle_request_defer():164] handle defer: 1
2023-03-14 15:32:04,370 DEBUG   SenderThread:26364 [sender.py:send_request():249] send_request: defer
2023-03-14 15:32:04,370 INFO    SenderThread:26364 [sender.py:send_request_defer():388] handle sender defer: 1
2023-03-14 15:32:04,370 INFO    SenderThread:26364 [sender.py:transition_state():392] send defer: 2
2023-03-14 15:32:04,370 DEBUG   HandlerThread:26364 [handler.py:handle_request():141] handle_request: defer
2023-03-14 15:32:04,370 INFO    HandlerThread:26364 [handler.py:handle_request_defer():164] handle defer: 2
2023-03-14 15:32:04,370 DEBUG   SenderThread:26364 [sender.py:send_request():249] send_request: defer
2023-03-14 15:32:04,370 INFO    SenderThread:26364 [sender.py:send_request_defer():388] handle sender defer: 2
2023-03-14 15:32:04,370 INFO    SenderThread:26364 [sender.py:transition_state():392] send defer: 3
2023-03-14 15:32:04,370 DEBUG   HandlerThread:26364 [handler.py:handle_request():141] handle_request: defer
2023-03-14 15:32:04,370 INFO    HandlerThread:26364 [handler.py:handle_request_defer():164] handle defer: 3
2023-03-14 15:32:04,370 DEBUG   SenderThread:26364 [sender.py:send_request():249] send_request: defer
2023-03-14 15:32:04,370 INFO    SenderThread:26364 [sender.py:send_request_defer():388] handle sender defer: 3
2023-03-14 15:32:04,370 INFO    SenderThread:26364 [sender.py:transition_state():392] send defer: 4
2023-03-14 15:32:04,370 DEBUG   HandlerThread:26364 [handler.py:handle_request():141] handle_request: defer
2023-03-14 15:32:04,370 INFO    HandlerThread:26364 [handler.py:handle_request_defer():164] handle defer: 4
2023-03-14 15:32:04,370 DEBUG   SenderThread:26364 [sender.py:send():235] send: summary
2023-03-14 15:32:04,370 INFO    SenderThread:26364 [sender.py:_save_file():949] saving file wandb-summary.json with policy end
2023-03-14 15:32:04,370 DEBUG   SenderThread:26364 [sender.py:send_request():249] send_request: defer
2023-03-14 15:32:04,370 INFO    SenderThread:26364 [sender.py:send_request_defer():388] handle sender defer: 4
2023-03-14 15:32:04,370 INFO    SenderThread:26364 [sender.py:transition_state():392] send defer: 5
2023-03-14 15:32:04,370 DEBUG   HandlerThread:26364 [handler.py:handle_request():141] handle_request: defer
2023-03-14 15:32:04,370 INFO    HandlerThread:26364 [handler.py:handle_request_defer():164] handle defer: 5
2023-03-14 15:32:04,370 DEBUG   SenderThread:26364 [sender.py:send_request():249] send_request: defer
2023-03-14 15:32:04,370 INFO    SenderThread:26364 [sender.py:send_request_defer():388] handle sender defer: 5
2023-03-14 15:32:04,483 DEBUG   HandlerThread:26364 [handler.py:handle_request():141] handle_request: poll_exit
2023-03-14 15:32:04,499 INFO    Thread-7  :26364 [dir_watcher.py:_on_file_modified():269] file/dir modified: C:\Users\jaydenpark\Documents\GitHub\disaster_tweet\wandb\run-20230314_153057-3kdb8mwr\files\output.log
2023-03-14 15:32:04,499 INFO    Thread-7  :26364 [dir_watcher.py:_on_file_modified():269] file/dir modified: C:\Users\jaydenpark\Documents\GitHub\disaster_tweet\wandb\run-20230314_153057-3kdb8mwr\files\wandb-summary.json
2023-03-14 15:32:04,582 ERROR   SenderThread:26364 [internal_api.py:execute():143] 409 response executing GraphQL.
2023-03-14 15:32:04,582 ERROR   SenderThread:26364 [internal_api.py:execute():144] {"errors":[{"message":"run respwill/disaster_tweet_classification/3kdb8mwr was previously created and deleted; try a new run name","path":["upsertBucket"]}],"data":{"upsertBucket":null}}
2023-03-14 15:32:05,376 INFO    WriterThread:26364 [datastore.py:close():279] close: C:\Users\jaydenpark\Documents\GitHub\disaster_tweet\wandb\run-20230314_153057-3kdb8mwr\run-3kdb8mwr.wandb
2023-03-14 15:32:05,489 INFO    HandlerThread:26364 [handler.py:finish():806] shutting down handler
2023-03-14 15:32:05,489 ERROR   MainThread:26364 [internal.py:wandb_internal():165] Thread SenderThread:
Traceback (most recent call last):
  File "C:\Users\jaydenpark\Anaconda3\envs\nlp3\lib\site-packages\wandb\apis\normalize.py", line 22, in wrapper
    return func(*args, **kwargs)
  File "C:\Users\jaydenpark\Anaconda3\envs\nlp3\lib\site-packages\wandb\sdk\internal\internal_api.py", line 1319, in upsert_run
    response = self.gql(mutation, variable_values=variable_values, **kwargs)
  File "C:\Users\jaydenpark\Anaconda3\envs\nlp3\lib\site-packages\wandb\sdk\lib\retry.py", line 108, in __call__
    result = self._call_fn(*args, **kwargs)
  File "C:\Users\jaydenpark\Anaconda3\envs\nlp3\lib\site-packages\wandb\sdk\internal\internal_api.py", line 140, in execute
    return self.client.execute(*args, **kwargs)
  File "C:\Users\jaydenpark\Anaconda3\envs\nlp3\lib\site-packages\wandb\vendor\gql-0.2.0\wandb_gql\client.py", line 52, in execute
    result = self._get_result(document, *args, **kwargs)
  File "C:\Users\jaydenpark\Anaconda3\envs\nlp3\lib\site-packages\wandb\vendor\gql-0.2.0\wandb_gql\client.py", line 60, in _get_result
    return self.transport.execute(document, *args, **kwargs)
  File "C:\Users\jaydenpark\Anaconda3\envs\nlp3\lib\site-packages\wandb\vendor\gql-0.2.0\wandb_gql\transport\requests.py", line 39, in execute
    request.raise_for_status()
  File "C:\Users\jaydenpark\Anaconda3\envs\nlp3\lib\site-packages\requests\models.py", line 960, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 409 Client Error: Conflict for url: https://api.wandb.ai/graphql

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\jaydenpark\Anaconda3\envs\nlp3\lib\site-packages\wandb\sdk\internal\internal_util.py", line 51, in run
    self._run()
  File "C:\Users\jaydenpark\Anaconda3\envs\nlp3\lib\site-packages\wandb\sdk\internal\internal_util.py", line 102, in _run
    self._process(record)
  File "C:\Users\jaydenpark\Anaconda3\envs\nlp3\lib\site-packages\wandb\sdk\internal\internal.py", line 310, in _process
    self._sm.send(record)
  File "C:\Users\jaydenpark\Anaconda3\envs\nlp3\lib\site-packages\wandb\sdk\internal\sender.py", line 237, in send
    send_handler(record)
  File "C:\Users\jaydenpark\Anaconda3\envs\nlp3\lib\site-packages\wandb\sdk\internal\sender.py", line 251, in send_request
    send_handler(record)
  File "C:\Users\jaydenpark\Anaconda3\envs\nlp3\lib\site-packages\wandb\sdk\internal\sender.py", line 411, in send_request_defer
    self.debounce()
  File "C:\Users\jaydenpark\Anaconda3\envs\nlp3\lib\site-packages\wandb\sdk\internal\sender.py", line 320, in debounce
    self._debounce_config()
  File "C:\Users\jaydenpark\Anaconda3\envs\nlp3\lib\site-packages\wandb\sdk\internal\sender.py", line 326, in _debounce_config
    self._api.upsert_run(
  File "C:\Users\jaydenpark\Anaconda3\envs\nlp3\lib\site-packages\wandb\apis\normalize.py", line 24, in wrapper
    raise CommError(err.response, err)
wandb.errors.CommError: <Response [409]>
2023-03-14 15:32:07,506 INFO    MainThread:26364 [internal.py:handle_exit():80] Internal process exited
