2023-03-14 15:30:57,335 INFO    MainThread:21752 [wandb_setup.py:_flush():76] Loading settings from C:\Users\jaydenpark\.config\wandb\settings
2023-03-14 15:30:57,335 INFO    MainThread:21752 [wandb_setup.py:_flush():76] Loading settings from C:\Users\jaydenpark\Documents\GitHub\disaster_tweet\wandb\settings
2023-03-14 15:30:57,335 INFO    MainThread:21752 [wandb_setup.py:_flush():76] Loading settings from environment variables: {}
2023-03-14 15:30:57,335 INFO    MainThread:21752 [wandb_setup.py:_flush():76] Inferring run settings from compute environment: {'program': '<python with no main file>'}
2023-03-14 15:30:57,335 INFO    MainThread:21752 [wandb_init.py:_log_setup():428] Logging user logs to C:\Users\jaydenpark\Documents\GitHub\disaster_tweet\wandb\run-20230314_153057-3kdb8mwr\logs\debug.log
2023-03-14 15:30:57,336 INFO    MainThread:21752 [wandb_init.py:_log_setup():429] Logging internal logs to C:\Users\jaydenpark\Documents\GitHub\disaster_tweet\wandb\run-20230314_153057-3kdb8mwr\logs\debug-internal.log
2023-03-14 15:30:57,336 INFO    MainThread:21752 [wandb_init.py:_jupyter_setup():378] configuring jupyter hooks <wandb.sdk.wandb_init._WandbInit object at 0x000001F463880790>
2023-03-14 15:30:57,336 INFO    MainThread:21752 [wandb_init.py:init():462] calling init triggers
2023-03-14 15:30:57,336 INFO    MainThread:21752 [wandb_init.py:init():465] wandb.init called with sweep_config: {}
config: {'learning_rate': 1e-07, 'data_size': 1, 'batch_size': 128}
2023-03-14 15:30:57,336 INFO    MainThread:21752 [wandb_init.py:init():515] starting backend
2023-03-14 15:30:57,336 INFO    MainThread:21752 [backend.py:_multiprocessing_setup():97] multiprocessing start_methods=spawn, using: spawn
2023-03-14 15:30:57,338 INFO    MainThread:21752 [backend.py:ensure_launched():217] starting backend process...
2023-03-14 15:30:57,404 INFO    MainThread:21752 [backend.py:ensure_launched():222] started backend process with pid: 26364
2023-03-14 15:30:57,404 INFO    MainThread:21752 [wandb_init.py:init():525] backend started and connected
2023-03-14 15:30:57,419 INFO    MainThread:21752 [wandb_run.py:_label_probe_notebook():1089] probe notebook
2023-03-14 15:30:57,419 INFO    MainThread:21752 [wandb_run.py:_label_probe_notebook():1099] Unable to probe notebook: 'NoneType' object has no attribute 'get'
2023-03-14 15:30:57,419 INFO    MainThread:21752 [wandb_init.py:init():596] updated telemetry
2023-03-14 15:30:57,419 INFO    MainThread:21752 [wandb_init.py:init():627] communicating run to backend with 30 second timeout
2023-03-14 15:30:59,032 INFO    MainThread:21752 [wandb_run.py:_on_init():1924] communicating current version
2023-03-14 15:30:59,079 INFO    MainThread:21752 [wandb_run.py:_on_init():1928] got version response upgrade_message: "wandb version 0.13.11 is available!  To upgrade, please run:\n $ pip install wandb --upgrade"

2023-03-14 15:30:59,079 INFO    MainThread:21752 [wandb_init.py:init():662] starting run threads in backend
2023-03-14 15:30:59,347 INFO    MainThread:21752 [wandb_run.py:_console_start():1898] atexit reg
2023-03-14 15:30:59,348 INFO    MainThread:21752 [wandb_run.py:_redirect():1771] redirect: SettingsConsole.WRAP
2023-03-14 15:30:59,348 INFO    MainThread:21752 [wandb_run.py:_redirect():1808] Wrapping output streams.
2023-03-14 15:30:59,349 INFO    MainThread:21752 [wandb_run.py:_redirect():1832] Redirects installed.
2023-03-14 15:30:59,349 INFO    MainThread:21752 [wandb_init.py:init():688] run started, returning control to user process
2023-03-14 15:30:59,350 INFO    MainThread:21752 [wandb_init.py:_pause_backend():341] pausing backend
2023-03-14 15:30:59,350 INFO    MainThread:21752 [jupyter.py:save_ipynb():377] not saving jupyter notebook
2023-03-14 15:30:59,358 INFO    MainThread:21752 [wandb_init.py:_resume_backend():350] resuming backend
2023-03-14 15:30:59,362 INFO    MainThread:21752 [wandb_init.py:_pause_backend():341] pausing backend
2023-03-14 15:30:59,362 INFO    MainThread:21752 [jupyter.py:save_ipynb():377] not saving jupyter notebook
2023-03-14 15:30:59,366 INFO    MainThread:21752 [wandb_init.py:_resume_backend():350] resuming backend
2023-03-14 15:30:59,546 INFO    MainThread:21752 [wandb_init.py:_pause_backend():341] pausing backend
2023-03-14 15:30:59,546 INFO    MainThread:21752 [jupyter.py:save_ipynb():377] not saving jupyter notebook
2023-03-14 15:30:59,556 INFO    MainThread:21752 [wandb_init.py:_resume_backend():350] resuming backend
2023-03-14 15:31:06,909 INFO    MainThread:21752 [wandb_init.py:_pause_backend():341] pausing backend
2023-03-14 15:31:06,909 INFO    MainThread:21752 [jupyter.py:save_ipynb():377] not saving jupyter notebook
2023-03-14 15:31:06,914 INFO    MainThread:21752 [wandb_init.py:_resume_backend():350] resuming backend
2023-03-14 15:31:06,916 INFO    MainThread:21752 [wandb_init.py:_pause_backend():341] pausing backend
2023-03-14 15:31:06,916 INFO    MainThread:21752 [jupyter.py:save_ipynb():377] not saving jupyter notebook
2023-03-14 15:32:04,314 INFO    MainThread:21752 [wandb_run.py:_atexit_cleanup():1867] got exitcode: 0
2023-03-14 15:32:04,316 INFO    MainThread:21752 [wandb_run.py:_restore():1839] restore
2023-03-14 15:32:04,370 INFO    MainThread:21752 [wandb_run.py:_on_finish():1996] got exit ret: file_counts {
  wandb_count: 1
}
pusher_stats {
  uploaded_bytes: 592
  total_bytes: 592
}

